wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.17.9
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726090132
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      3:
      - 13
      - 23
      4: 3.10.4
      5: 0.17.9
      6: 4.44.2
      8:
      - 5
      13: linux-x86_64
